
name: Learning

on:
  push:
    branches:
      - trigger
  # schedule every 7 minutes

jobs:
  trigger-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        ref: trigger
    - name: Perform action
      run: |
        git commit --allow-empty -m "trigger action"
        git push origin trigger

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ master, test ]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Perform action
        run: cat foo.rb
