
name: Learning

on:
  schedule:
    # trigger every 5 minutes
    - cron:  '*/5 * * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ "master", "test" ]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Perform action
        run: cat foo.rb
