
name: Learning

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        food:
          - pizza
          - beer
          - ice cream
          - salad
    steps:
      - name: Output Value
        run: |
          echo I am a little teapot $${ matrix.food } and stout
