
name: Learning

on:
  push:
    branches:
      - trigger
  # schedule every 7 minutes

jobs:
  trigger-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        ref: trigger
    - name: Perform action
      run: |
        git config user.email "commit-trigger-bot@example.com"
        git config user.name "Commit Trigger Bot"

        git commit --allow-empty -m "trigger action at $(date +%s)"
        git push origin trigger

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ master, test ]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Perform action
        run: cat foo.rb
