
name: Learning

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        food:
          - pizza
          - beer
          - ice cream
    steps:
      - name: First way
        run: echo $${ matrix.food }

      - name: Second way
        env:
          NAME: $${ matrix.food }
        run: echo $NAME
