
name: Learning

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        food:
          - pizza
          - beer
          - ice cream
    steps:
      - name: Output Value
        env:
          NAME: $${matrix.food}
        run: |
          echo I am a little teapot $NAME and stout
